// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';

export interface IFooterFields {
  /** Entry Name */
  entryName: string;

  /** Logo Image */
  logoImage: Asset;

  /** Logo Link URL */
  logoLinkUrl: string;

  /** Contact Section Title */
  contactSectionTitle: string;

  /** Navigation Links */
  navigationLinks: Entry<{ [fieldId: string]: unknown }>[];

  /** Customer Support Content */
  customerSupportContent: string;

  /** Privacy Section Title */
  privacySectionTitle: string;

  /** Privacy Links */
  privacyLinks: Entry<{ [fieldId: string]: unknown }>[];

  /** Social Section Title */
  socialSectionTitle: string;

  /** Social Links */
  socialLinks: Entry<{ [fieldId: string]: unknown }>[];
}

/** Footer content */

export interface IFooter extends Entry<IFooterFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'footer';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IHeroSectionFields {
  /** Entry Name */
  entryName: string;

  /** Headline */
  headline: string;

  /** Subheadline */
  subheadline: string;

  /** Background image */
  backgroundImage: Asset;

  /** Alt text */
  altText: string;

  /** Scroll label */
  scrollLabel?: string | undefined;
}

/** Top banner with headline, subheadline, background image */

export interface IHeroSection extends Entry<IHeroSectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'heroSection';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IHomePageFields {
  /** Entry Name */
  entryName: string;

  /** Key */
  key: string;

  /** Hero section */
  heroSection: IHeroSection;

  /** Metadata */
  metadata: IMetaAndShare;
}

/** Main page that defines the title, slug, metadata, sections and etc... Sections are ordered to build the page layout. */

export interface IHomePage extends Entry<IHomePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'homePage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILinkFields {
  /** Link Name */
  linkName: string;

  /** Display Text */
  displayText: string;

  /** URL */
  url: string;

  /** Icon */
  icon?: Asset | undefined;

  /** Link Behavior */
  linkBehavior: 'sameTab' | 'newTab';
}

export interface ILink extends Entry<ILinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'link';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IMetaAndShareFields {
  /** Entry Name */
  entryName: string;

  /** Meta Title */
  metaTitle: string;

  /** Meta Description */
  metaDescription?: string | undefined;

  /** Meta Keywords */
  metaKeywords?: string[] | undefined;

  /** OG Image */
  ogImage?: Asset | undefined;
}

/** Metadata and Share content at the page level */

export interface IMetaAndShare extends Entry<IMetaAndShareFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'metaAndShare';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE =
  | 'footer'
  | 'heroSection'
  | 'homePage'
  | 'link'
  | 'metaAndShare';

export type IEntry = IFooter | IHeroSection | IHomePage | ILink | IMetaAndShare;

export type LOCALE_CODE = 'en-US' | 'es-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
