export const NEVADA_CITIES = [
  'Nevada',
  'Alamo',
  'Amargosa Valley',
  'Austin',
  'Baker',
  'Battle Mountain',
  'Beatty',
  'Beaverdam',
  'Bennett Springs',
  'Blue Diamond',
  'Boulderity',
  'Bunkervile',
  'Cal-Nev-Ari',
  'Gallente',
  'Carlin',
  'Carson',
  'Garter Springs',
  'Cold Springs',
  'Crescent Valley',
  'Crystal Bay',
  'Dayton',
  'Denio',
  'Double Spring',
  'Dry Valley',
  'Dyer',
  'East Valley',
  'Eko',
  'fy',
  'Empire',
  'Enterprise',
  'Eureka',
  'Fallon Station',
  'Fallon',
  'Fernley',
  'Fish Springs',
  'Fort MeDermitt',
  'Gabbs',
  'Gardnerville',
  'Gardnerville Ranchos',
  'Genoa',
  'Gerlach',
  'Glenbrook',
  'Golconda',
  'Golden Valley',
  'Golafield',
  'Goodsprings',
  'Grass Valley',
  'Hawthorne',
  'Henderson',
  'Hiko',
  'Humboldt River Ranch',
  'Imlay',
  'Incline village',
  'Indian Hills',
  'Indian Springs',
  'Jackpot',
  'Johnson Lane',
  'Kingsbury',
  'Kingston',
  'Lakeridge',
  'Lamaille',
  'Las Vegas',
  'Laughlin',
  'Lemmon Valley',
  'Loganreek',
  'Lovelock',
  'und',
  'MeDermitt',
  'MeGill',
  'Mesquite',
  'Mina',
  'Minden',
  'Moapa Town',
  'Moapa Valley',
  'Mogul',
  'Montello',
  'Mountharleston',
  'Mount Wilson',
  'Mountainity',
  'Nellis AFB.',
  'Nelson',
  'Nixon',
  'North Las Vegas',
  'Oasis',
  'Orovada',
  'Osino',
  'Owyhee',
  'Pahrump',
  'Panaca',
  'Paradise',
  'Paradise Valley',
  'Pioche',
  'Preston',
  'Rachel',
  'Reno',
  'Round Hill Village',
  'Ruhenstroth',
  'uth',
  'Sandy Valley',
  'Schure',
  'Searchlight',
  'Silverity',
  'Silver Peak',
  'Silver Springs',
  'Skyland',
  'Smith Valley',
  'Spanish Springs',
  'Sparks',
  'Springreek',
  'Spring Valley',
  'Stagecoach',
  'Stateline',
  'Summerlin South',
  'Sun Valley',
  'Sunrise Manor',
  'sutcliffe',
  'Tonopah',
  'Topaz Lake',
  'Topaz Ranch EstatesD',
  'Unionville',
  'Ussine',
  'Valmy',
  'Verdi',
  'Virginia Gty',
  'Wadsworth',
  'Walker Lake',
  'Washoe Valley',
  'Wells',
  'West Wendover',
  'Whitney',
  'Winchester',
  'Winnemucca',
  'Yerington',
  'Zephyrove'
];

export const WASHINGTON_CITIES = [
  'Airway Heights',
  'Algona',
  'Anacortes',
  'Arlington',
  'Auburn',
  'Bainbridge Island',
  'Battle Ground',
  'Bellevue',
  'Bellingham',
  'Black Diamond',
  'Blaine',
  'Bonney Lake',
  'Bothell',
  'Bremerton',
  'Brier',
  'Buckley',
  'Burlington',
  'Camas',
  'Centralia',
  'Cheney',
  'Clarkston',
  'College Place',
  'Colville',
  'Concrete',
  'Connell',
  'Cosmopolis',
  'Covington',
  'Darrington',
  'Davenport',
  'Dayton',
  'Deer Park',
  'Des Moines',
  'DuPont',
  'Duvall',
  'East Wenatchee',
  'Eatonville',
  'Edgewood',
  'Edmonds',
  'Ellensburg',
  'Elma',
  'Enumclaw',
  'Ephrata',
  'Everett',
  'Federal Way',
  'Fife',
  'Fircrest',
  'Forks',
  'Friday Harbor',
  'Gig Harbor',
  'Gold Bar',
  'Goldendale',
  'Grand Coulee',
  'Grandview',
  'Granite Falls',
  'Issaquah',
  'Kalama',
  'Kelso',
  'Kenmore',
  'Kennewick',
  'Kent',
  'Kettle Falls',
  'Kirkland',
  'Kittitas',
  'La Center',
  'Lacey',
  'Lake Forest Park',
  'Lake Stevens',
  'Lakewood',
  'Langley',
  'Leavenworth',
  'Liberty Lake',
  'Long Beach',
  'Longview',
  'Lyman',
  'Lynden',
  'Lynnwood',
  'Mabton',
  'Maple Valley',
  'Marysville',
  'McCleary',
  'McKenna',
  'Medical Lake',
  'Medina',
  'Mercer Island',
  'Mesa',
  'Metaline',
  'Metaline Falls',
  'Mill Creek',
  'Millwood',
  'Milton',
  'Monroe',
  'Montesano',
  'Morton',
  'Moses Lake',
  'Mossyrock',
  'Mount Vernon',
  'Mountlake Terrace',
  'Moxee',
  'Mukilteo',
  'Newcastle',
  'Newport',
  'Nooksack',
  'Normandy Park',
  'North Bend',
  'North Bonneville',
  'Oak Harbor',
  'Ocean Shores',
  'Odessa',
  'Okanogan',
  'Olympia',
  'Omak',
  'Orting',
  'Othello',
  'Pacific',
  'Palouse',
  'Pasco',
  'Pateros',
  'Pomeroy',
  'Port Angeles',
  'Port Orchard',
  'Port Townsend',
  'Poulsbo',
  'Prosser',
  'Pullman',
  'Puyallup',
  'Quincy',
  'Rainier',
  'Raymond',
  'Redmond',
  'Renton',
  'Republic',
  'Richland',
  'Ridgefield',
  'Ritzville',
  'Riverside',
  'Rochester',
  'Rock Island',
  'Roslyn',
  'Roy',
  'Royal City',
  'Ruston',
  'Sammamish',
  'SeaTac',
  'Seattle',
  'Sedro-Woolley',
  'Selah',
  'Sequim',
  'Shelton',
  'Shoreline',
  'Silverdale',
  'Snohomish',
  'Snoqualmie',
  'Soap Lake',
  'South Bend',
  'Spangle',
  'Spokane',
  'Spokane Valley',
  'Sprague',
  'Springdale',
  'St. John',
  'Stanwood',
  'Steilacoom',
  'Stevenson',
  'Sultan',
  'Sumas',
  'Sumner',
  'Sunnyside',
  'Tacoma',
  'Tekoa',
  'Tenino',
  'Tieton',
  'Toledo',
  'Tonasket',
  'Toppenish',
  'Tukwila',
  'Tumwater',
  'Union Gap',
  'University Place',
  'Vader',
  'Vancouver',
  'Vashon',
  'Waitsburg',
  'Walla Walla',
  'Wapato',
  'Warden',
  'Washougal',
  'Wenatchee',
  'West Richland',
  'Westport',
  'White Salmon',
  'Wilbur',
  'Wilkeson',
  'Wilson Creek',
  'Winlock',
  'Winthrop',
  'Woodinville',
  'Woodland',
  'Woodway',
  'Yakima',
  'Yarrow Point',
  'Yelm',
  'Zillah'
];
